//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doc_Builder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mil_Templates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mil_Templates()
        {
            this.Mil_ReadyDocuments = new HashSet<Mil_ReadyDocuments>();
        }
    
        public int ID { get; set; }
        public string Header { get; set; }
        public string TypeName { get; set; }
        public string Path { get; set; }
        public string FieldData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mil_ReadyDocuments> Mil_ReadyDocuments { get; set; }
        public virtual Mil_Type Mil_Type { get; set; }
    }
}
