//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doc_Builder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mil_ReadyDocuments
    {
        public int ID { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string Path { get; set; }
    
        public virtual MIL_Employees MIL_Employees { get; set; }
        public virtual Mil_Templates Mil_Templates { get; set; }
    }
}
