//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doc_Builder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class User10_Sgr1Entities : DbContext
    {
        public User10_Sgr1Entities()
            : base("name=User10_Sgr1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MIL_Employees> MIL_Employees { get; set; }
        public virtual DbSet<Mil_ReadyDocuments> Mil_ReadyDocuments { get; set; }
        public virtual DbSet<Mil_Templates> Mil_Templates { get; set; }
        public virtual DbSet<Mil_Type> Mil_Type { get; set; }
        public virtual DbSet<Mil_UsersDoc> Mil_UsersDoc { get; set; }
    }
}
